In [1]:
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

# Load the model
model = load_model('converted_keras/keras_model.h5')

In [30]:
print(model.summary())
# print('*-*' * 10)
# print(model.weights)
# print('*-*' * 10)
model.get_config()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 sequential_1 (Sequential)   (None, 1280)              410208    
                                                                 
 sequential_3 (Sequential)   (None, 2)                 128300    
                                                                 
Total params: 538,508
Trainable params: 524,428
Non-trainable params: 14,080
_________________________________________________________________
None


{'name': 'sequential_4',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 224, 224, 3),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'sequential_1_input'}},
  {'class_name': 'Sequential',
   'config': {'name': 'sequential_1',
    'layers': [{'class_name': 'InputLayer',
      'config': {'batch_input_shape': (None, 224, 224, 3),
       'dtype': 'float32',
       'sparse': False,
       'ragged': False,
       'name': 'model1_input'}},
     {'class_name': 'Functional',
      'config': {'name': 'model1',
       'layers': [{'class_name': 'InputLayer',
         'config': {'batch_input_shape': (None, 224, 224, 3),
          'dtype': 'float32',
          'sparse': False,
          'ragged': False,
          'name': 'input_1'},
         'name': 'input_1',
         'inbound_nodes': []},
        {'class_name': 'ZeroPadding2D',
         'config': {'name': 'Conv1_pad',
          'trainable': True,
          'dtype': 'float32',
     

In [31]:
# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

from glob import glob

fileList = glob('converted_keras/*.jpg')

for file in fileList:
    image = Image.open(file)
    size = (224, 224)
    image = ImageOps.fit(image, size, Image.ANTIALIAS)
    image_array = np.asarray(image)
    normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
    data[0] = normalized_image_array

    className = ['남자', '여자']
    prediction = model.predict(data)
    if prediction[0][0] > 0.5:
        print(className[0])
    else:
        print(className[1])
    print(prediction)
    print(className[np.argmax(prediction)])

1/1 [==============================] - 0s 62ms/step
남자
[[9.9999988e-01 8.7646825e-08]]
남자
1/1 [==============================] - 0s 32ms/step


C:\Users\HP\AppData\Local\Temp\ipykernel_14892\4222742396.py:13: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  image = ImageOps.fit(image, size, Image.ANTIALIAS)


남자
[[9.9999690e-01 3.1494078e-06]]
남자
1/1 [==============================] - 0s 57ms/step
남자
[[9.9983668e-01 1.6328166e-04]]
남자
1/1 [==============================] - 0s 37ms/step
여자
[[1.8296033e-06 9.9999821e-01]]
여자
1/1 [==============================] - 0s 34ms/step
여자
[[1.0535279e-04 9.9989462e-01]]
여자
1/1 [==============================] - 0s 44ms/step
여자
[[0.10414226 0.89585775]]
여자


## python opencv

- Open Source Computer Vision Library

In [32]:
!pip install opencv-python

In [18]:
import cv2

# haarcascade 불러오기
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

# 이미지 불러오기
img = cv2.imread('converted_keras/group2.jpeg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 얼굴 찾기
faces = face_cascade.detectMultiScale(gray, 1.3, 5)
# print(faces)

# 폰트 색상 지정
blue = (255, 0, 0)
green= (0, 255, 0)
red= (0, 0, 255)
white= (255, 255, 255)
font = cv2.FONT_HERSHEY_PLAIN
img = cv2.putText(img, 'face_count: ' + str(len(faces)),s (10, 30), font, 2, blue, 1, cv2.LINE_AA)

result = 0
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x - 20, y - 20), (x + w + 20, y + h + 20), (255, 0, 0), 2)
    result += 1
    img = cv2.putText(img, str(result), (x, y - 30), font, 1, blue, 1, cv2.LINE_AA)
    # ROI (Region Of Interest)
    # 이미지 상에서 내가 관심있어하는 일부 영역
    roi_color = img[y:y + h, x:x + w]
    
    # roi_color이 teachable machine의 h5 모델에 넣는 사진자료가 됨
    # result는 모델의 예측결과
    cv2.imwrite('face_result/' + str(result) + '.jpg', roi_color)
    
# 영상 출력
cv2.imshow('image', img)

key = cv2.waitKey(0)
cv2.destroyAllWindows()