In [49]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([10, 98, 8, 2, 3, 4])

# w값 바꾸지 않기 위해 사용함, 검증용이며 실제에서는 seed하지 않음.
tf.random.set_seed(1234)

input_layer = tf.keras.layers.InputLayer(input_shape=(1, ))
hidden_layer1 = tf.keras.layers.Dense(units=4, activation='relu')
hidden_layer2 = tf.keras.layers.Dense(units=2, activation='relu')
output_layer = tf.keras.layers.Dense(units=1)

# activation이 없으면 활성화함수 wx+b가 되어있는 것임.
model = keras.Sequential(
    [input_layer, hidden_layer1, hidden_layer2, output_layer])

model.compile(  #optimizer='adam',
    loss='mse', metrics=['accuracy'])

print(model.fit(x, y))
print(model.predict(x))
print(model.evaluate(x, y))

1/1 [==============================] - 0s 29ms/step
[[0.00316228]
 [0.00316228]
 [0.00316228]
 [0.00316228]
 [0.00316228]
 [0.00316228]]
1/1 [==============================] - 0s 58ms/step - loss: 1632.7017 - accuracy: 0.0000e+00
[1632.70166015625, 0.0]


In [14]:
# 모델의 구성요소를 보여줌(h5로 저장된 모델도 이렇게 볼 수 있음.)
model.get_config()

{'name': 'sequential_3',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 1),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'input_5'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_12',
    'trainable': True,
    'dtype': 'float32',
    'units': 4,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_13',
    'trainable': True,
    'dtype': 'float32',
    'units': 2,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'confi

In [93]:
model.get_weights()

[array([[ 0.08334005, -0.29660565,  0.17884266, -0.56124383]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[-0.34927058, -0.7225988 ],
        [ 0.2960987 , -0.39196324],
        [-0.32647347, -0.73963904],
        [ 0.41159463,  0.43719316]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.2757995 ],
        [-0.55681044]], dtype=float32),
 array([0.00316228], dtype=float32)]

In [95]:
model.get_layerb

<bound method Model.get_layer of <keras.engine.sequential.Sequential object at 0x000002CFC16A41C0>>

In [10]:
model.weights

[<tf.Variable 'dense_12/kernel:0' shape=(1, 4) dtype=float32, numpy=
 array([[ 0.08334005, -0.29660565,  0.17884266, -0.56124383]],
       dtype=float32)>,
 <tf.Variable 'dense_12/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_13/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[-0.34927058, -0.7225988 ],
        [ 0.2960987 , -0.39196324],
        [-0.32647347, -0.73963904],
        [ 0.41159463,  0.43719316]], dtype=float32)>,
 <tf.Variable 'dense_13/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_14/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[ 0.2757995 ],
        [-0.55681044]], dtype=float32)>,
 <tf.Variable 'dense_14/bias:0' shape=(1,) dtype=float32, numpy=array([0.00316228], dtype=float32)>]

In [92]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 4)                 8         
                                                                 
 dense_16 (Dense)            (None, 2)                 10        
                                                                 
 dense_17 (Dense)            (None, 1)                 3         
                                                                 
Total params: 21
Trainable params: 21
Non-trainable params: 0
_________________________________________________________________


In [11]:
intermediate_layer_model = tf.keras.Model(inputs=model.input, outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(x)

print('\n======== Outputs of Hidden Layer ========')
print(intermediate_output)


======== Outputs of Hidden Layer ========
tf.Tensor(
[[0.08334005 0.         0.17884266 0.        ]
 [0.1666801  0.         0.35768533 0.        ]
 [0.25002015 0.         0.536528   0.        ]
 [0.3333602  0.         0.71537066 0.        ]
 [0.41670024 0.         0.8942133  0.        ]
 [0.5000403  0.         1.073056   0.        ]], shape=(6, 4), dtype=float32)


In [12]:
intermediate_layer_model = tf.keras.Model(inputs=model.input, outputs=model.layers[1].output)
intermediate_output = intermediate_layer_model(x)

print('\n======== Outputs of Hidden Layer ========')
print(intermediate_output)


======== Outputs of Hidden Layer ========
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]], shape=(6, 2), dtype=float32)


In [13]:
intermediate_layer_model = tf.keras.Model(inputs=model.input, outputs=model.layers[2].output)
intermediate_output = intermediate_layer_model(x)

print('\n======== Outputs of Hidden Layer ========')
print(intermediate_output)


======== Outputs of Hidden Layer ========
tf.Tensor(
[[0.00316228]
 [0.00316228]
 [0.00316228]
 [0.00316228]
 [0.00316228]
 [0.00316228]], shape=(6, 1), dtype=float32)


In [98]:
# 0번째 layer의 bias 확인
model.layers[0].bias

<tf.Variable 'dense_15/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [97]:
# 1번째 layer의 weights 확인
model.layers[0].weights

[<tf.Variable 'dense_15/kernel:0' shape=(1, 4) dtype=float32, numpy=
 array([[ 0.08334005, -0.29660565,  0.17884266, -0.56124383]],
       dtype=float32)>,
 <tf.Variable 'dense_15/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]